### ISSUE TITLE
Expected release date

### ISSUE THREAD

**Issue by Anonnoname** [lucidrains/VN-transformer#1]
Hi lucidrains, is there an expected release date for this project. I am currently implementing the VN-transformer as well, but facing some technical difficulties.

**Comment by dennisushi** [comment]
> Hi lucidrains, is there an expected release date for this project. I am currently implementing the VN-transformer as well, but facing some technical difficulties.

Did you manage to implement it?

**Comment by lucidrains** [comment]
@dennisushi @Anonnoname hey, sorry for getting back to this project so late

going to finish this up by latest next week's end

**Comment by lucidrains** [comment]
seems like there's a lot of interest in it!

**Comment by lucidrains** [comment]
also, just so you are all aware, i think there's been kind of a small breakthrough in the equivariance space https://arxiv.org/abs/2302.03655

**Comment by lucidrains** [comment]
ok, almost there, save for the early or late fusion of non-spatial features

**Comment by lucidrains** [comment]
ok, it is done
